### ISSUE TITLE
pytorch code

### ISSUE THREAD

**Issue by SensenHao** [PengtaoJiang/OAA#1]
Hello, thank you very much for sharing the code. When can you share the pytorch code?

**Comment by PengtaoJiang** [comment]
@SensenHao 
Hi, Thanks for following our work. We are recently focusing on implementing the pytorch code of OAA. We plan to publish the code before the ICCV conference time. (2019-10-27)  
Best wishes...
Peng-Tao Jiang

**Comment by SensenHao** [comment]
Thank you very much for your reply! @PengtaoJiang

**Comment by UdonDa** [comment]
Hello, thank you for sharing your code and some explamations.
I have a question.
When do you publish the pytorch implementation?

**Comment by GuoleiSun** [comment]
Hi Peng-Tao,
Thanks for the interesting work. I am also expecting the pytorch code for your work.

**Comment by PengtaoJiang** [comment]
@GuoleiSun @UdonDa @SensenHao   Hi, I am now trying to reproduce the performance in my paper.  The attention map from the PyTorch code is slightly different that from Caffe.  If I can't reproduce my score perfectly, I will upload the code with a similar performance next weekend.

**Comment by UdonDa** [comment]
Thanks!!
I look forward to it!

**Comment by GuoleiSun** [comment]
Thanks, I also look forward to it
