### ISSUE TITLE
Cool heatmaps

### ISSUE THREAD

**Issue by lianxxx** [PengtaoJiang/OAA#6]
Your work is very impressive and thank you for your code.
The heatmaps in your paper look very cool. Could you kindly provide the code for visualizing those heatmaps?

**Comment by PengtaoJiang** [comment]
Hi, @lianxxx . I have upload this code. Check [it](https://github.com/PengtaoJiang/OAA/tree/master/examples/oaa/color).

**Comment by lianxxx** [comment]
> Hi, @lianxxx . I have upload this code. Check [it](https://github.com/PengtaoJiang/OAA/tree/master/examples/oaa/color).

Thank you very much.
