### ISSUE TITLE
backbone used to generate psudo-gt segmentation label

### ISSUE THREAD

**Issue by GuoleiSun** [PengtaoJiang/OAA#7]
In the paper, you reported two results: vgg16 and resnet101. In 3.1, it is mentioned that vgg-16 with several more convolutions is used to generate attention cues. 
My question is: for both vgg16 and resnet101 result, do you use the same attention cues, generated by vgg-16? Or you use vgg16 for generating attention and vgg-16 for fully segmentation model => vgg-16 resuts, and resnet-101 for generating attention and resnet-101 for fully segmentation model => result101 results?

Thanks

**Comment by PengtaoJiang** [comment]
@GuoleiSun Hi, for both vgg16 and resnet101 segmentation results, we use the same attention cues generated by vgg-16.
