### ISSUE TITLE
Questions about the training setting of segmentation networks

### ISSUE THREAD

**Issue by FateDawnLeon** [PengtaoJiang/OAA#8]
Hi Pengtao,

Thank you for open sourcing your codes！
I am reproducing the segmentation results using your codes provided in 'examples/seg/'.

But I find your code is not consistent with settings described in your ICCV 2019 paper. For example, the following codes shown in 'examples/seg/exp1/train.prototxt'
![image](https://user-images.githubusercontent.com/12904612/82404811-d1910180-9a94-11ea-9402-e8d574569dd2.png)
Here, I do not understand why setting the batchsize to 1？

In the paper, the bacthsize is said to be 10 and iterations be 15000. In order to reproduce your result, do I just need to reset the batchsize and iterations? Or are there any other settings requiring adjustment in the provided code?

Thank you for your patience. I would appreciate it very much if you clarify training settings.

**Comment by PengtaoJiang** [comment]
Hello, @FateDawnLeon:
    In examples/seg/exp1/solver.prototxt, the parameter `iter_size=10`,  practical_batch_size = iter_size * batch_size.

**Comment by FateDawnLeon** [comment]
Thank you for the explanation. I am done with it.
